language: node_js
sudo: false
node_js:
  - 5
cache:
  directories:
    - node_modules
env:
  global:
    - 'NPM_CONFIG_PROGRESS="false"'
    # GITHUB_TOKEN
    - secure: H+Kqx7pwfafnBYQAMVMCXWiEZ25DjPqO2e0wJSepTWll1lWO+7D57+6wSJDVuslqDogKYMCLL43cSOXRUtghiYXdwvO5SRurCyWektc9LLGf2PV4KOJlxM7fJSWf8o9u2DBJjaZKNuG6OSL87snCTBcEUu4CB0QBj+li9fuy1OUbvy0MZRskhcdw+Z0jKXcmW+sZTkZupuTDU9P4qS0G/v+lofQ6OQ3+YcFlCPp9LgOW/1UoIcRi8JPTwJzskBoZr5ACd8/QIFjeoibwwX4ODX+KThsNCfI5MOic7Su3KX3gvWb9KGBeoiv6zisA7iUoAyeJr3r0M6GRspneaxR8buHZ+1rzze/xKCdKiBlhuv6M6oknDNQqzfxrV+DZsl6qe/HqlxqXwerDXA2vppjQ/a290/jc12rPPzUUWzJNfiBvmUQUr2+ZcB2borwaZEyi+nmxTv1pfQgpPY9I3lzq3ehZrtK07tTahrX7iWi8QhzI3/vRP4YluUcrYKT8PmfM5Btlklm51hO/xUC0cBQB+DYq5O9FNZVozasagM/ZgcFXFgmG+nfWbum3WtTLM3n3OFvem1rxm5szbJiHJrU/Fb9nmID+0H91sqDCiHBw56/iI0H5gT+JyZR0AKkmhvUdrisVioPLa0WWeBVTkA3ASFFLPCWSk3E7FEYn4lTTHHI=
before_install:
  - npm prune
before_deploy:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  'on':
    branch: master
    node: '5'
