language: node_js
sudo: false
node_js:
  - 5
cache:
  directories:
    - node_modules
env:
  global:
    - 'NPM_CONFIG_PROGRESS="false"'
    - secure: H+Kqx7pwfafnBYQAMVMCXWiEZ25DjPqO2e0wJSepTWll1lWO+7D57+6wSJDVuslqDogKYMCLL43cSOXRUtghiYXdwvO5SRurCyWektc9LLGf2PV4KOJlxM7fJSWf8o9u2DBJjaZKNuG6OSL87snCTBcEUu4CB0QBj+li9fuy1OUbvy0MZRskhcdw+Z0jKXcmW+sZTkZupuTDU9P4qS0G/v+lofQ6OQ3+YcFlCPp9LgOW/1UoIcRi8JPTwJzskBoZr5ACd8/QIFjeoibwwX4ODX+KThsNCfI5MOic7Su3KX3gvWb9KGBeoiv6zisA7iUoAyeJr3r0M6GRspneaxR8buHZ+1rzze/xKCdKiBlhuv6M6oknDNQqzfxrV+DZsl6qe/HqlxqXwerDXA2vppjQ/a290/jc12rPPzUUWzJNfiBvmUQUr2+ZcB2borwaZEyi+nmxTv1pfQgpPY9I3lzq3ehZrtK07tTahrX7iWi8QhzI3/vRP4YluUcrYKT8PmfM5Btlklm51hO/xUC0cBQB+DYq5O9FNZVozasagM/ZgcFXFgmG+nfWbum3WtTLM3n3OFvem1rxm5szbJiHJrU/Fb9nmID+0H91sqDCiHBw56/iI0H5gT+JyZR0AKkmhvUdrisVioPLa0WWeBVTkA3ASFFLPCWSk3E7FEYn4lTTHHI=
    - secure: J4T6RwZo3qE54FlaUWy1ttO5tvZ4ML183oLVpEqdht9+p34gDzCFrRxwi+Hdwy+eZZH05ebOOEjBC2t2X5lvUZzdvArdCdo2fqSCJ8HKB7L8P6zGo5o5u1elffBHyYBgUPY/aaMclypgW0xEe0gKTKB/w/fnFJsxwiP9ujST6tJ26tGiIhV0N4svIRj0uMijrWl0nhBw1QAofezJhBS77T+H9ObAVZEedIFFDsfa4VNKbFaMTmTwGGOBYK+BBPORYXW2GHTiukaZretNwj9KVWq2G8EdCUgf8JcRfzm3xBWq+cw1e2rRG/9+QXXNugHyiXT3w2fHRW/8+LnaJB134BB+FmkmExjrnImvQaPG31s1O/w54zZ/cQ5Tb8rzEEKkUiQlI0nrWiHRTWBIp0VXAW4z67h0Q6juFXqs2ckusN3UtrlMqDFe/AZIJKML+3P9nD9+RT/9mWkiCEno8fNzo6sKmsfCUavKdnQaoSZUqcazH0ICnEFYfV+HXW0YXjQ7g+26BxPvNF9BJXqIytwuDJZea9KHFxsbCVxWwrKR8HkX6VwCcUtOstd9+Inw7KiPjm5ctrbAaZ8iBaX7/R4dfk3O1wzFLBpVbVKWoGZTQTuvIGbeeD2+0QE4Eug6fmvqfRx6HAgBXJQi2Vau3KrCv0XL0evaGk1anwW/0kva2u8=
before_install:
  - npm prune
before_deploy:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  'on':
    branch: master
    node: '5'
